# dist: precise
language: go
go:
- 1.8

env:
  global:
  - SSH_KEY="pwnation"
  - GIT_NAME="Pwnation"
  - GIT_EMAIL="tzaoh1@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
 - sudo rm /usr/bin/python
 - sudo ln /usr/bin/python3 /usr/bin/python
 - sudo apt-get install python3 python3-pip
 - sudo pip3 install pygments
 - sudo pip3 install git+https://github.com/Pwnation/radare2-pygments-lexer.git
 - git clone --branch v2 https://github.com/go-yaml/yaml \$GOPATH/src/gopkg.in/yaml.v2
 - sudo apt-get install hugo
 - openssl aes-256-cbc -K $encrypted_969d6b0ccbdc_key -iv $encrypted_969d6b0ccbdc_iv -in pwnation.enc -out pwnation -d
script:
- git clone --branch source https://github.com/Pwnation/Pwnation.github.io.git
- hugo --ignoreCache
after_success:
- "./scripts/deploy.sh"
