# dist: precise
language: go
go:
- 1.8

env:
  global:
  - SSH_KEY="pwnation"
  - GIT_NAME="Pwnation"
  - GIT_EMAIL="tzaoh1@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
 - rm /usr/bin/python
 - ln /usr/bin/python3 /usr/bin/python
 - sudo pip install pygments
 - sudo pip --no-cache-dir install git+https://github.com/Pwnation/radare2-pygments-lexer.git
 - git clone --branch v2 https://github.com/go-yaml/yaml \$GOPATH/src/gopkg.in/yaml.v2
 - go get -u -v github.com/Pwnation/hugo
 - openssl aes-256-cbc -K $encrypted_88b4fd6fc50b_key -iv $encrypted_88b4fd6fc50b_iv -in pwnation.enc -out pwnation -d
script:
- git clone --branch source https://github.com/Pwnation/Pwnation.github.io.git
- hugo --ignoreCache
after_success:
- "./scripts/deploy.sh"
