baseurl = "http://Pwnation.github.io/"
languageCode = "en-us"
title = "Pwnation Site"
theme = "HugoMDL"
MetaDataFormat = "yaml"

googleAnalytics = "UA-103806632-1"

pygmentsUseClassic = true
pygmentsuseclasses = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableEmoji = true

[taxonomies]
tag = "tags"
post_category = "post_categories"
about_category = "about_categories"
project_category = "project_categories"

[permalinks]
	page = "/:title/"
	about = "/about/:filename"

[params]
  id = 1
  group = "Pwnation"
  avatar = "/images/blackHoodsIcon120x120.png"
  background = "/images/background.jpg"
  description = "A place to publish my incomprehensible ramblings" #meta description
  image = "/images/blackHoodsIcon120x120.png" #for frontpage profile card
  mdlPrimary = "grey"
  mdlSecondary = "orange"

  email = "pwn4tion@gmail.com"
  twitter = "https://twitter.com/PwnationBlog"
  github = "https://github.com/Pwnation"

  copyrightyear = "2017"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
