baseurl = "http://CuckooWorld.github.io/"
languageCode = "en-us"
title = "BlackHoods Site"
theme = "HugoMDL"
MetaDataFormat = "yaml"



[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "Bl4ckH00d5"
  avatar = "/images/blackHoodsIcon120x120.png"
  background = "/images/background.gif"
  description = "A place to publish my incomprehensible ramblings" #meta description
  image = "/images/blackHoodsIcon120x120.png" #for frontpage profile card
  mdlPrimary = "grey"
  mdlSecondary = "orange"

  email = "Firstname@example.com"
  twitter = "https://twitter.com/firstname_lastname"
  github = "https://github.com/BlackHoods"

  copyrightyear = "2017"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
